// react-unit-testing/src/Todo/TodoAppContainer.tsx
import React from 'react';
import loglevel from 'loglevel';
import TodoApp from './TodoApp';
import useTodoApp from './useTodoApp';

interface Props {

}

const TodoAppContainer: React.FC<Props> = () => {
  loglevel.debug('TodoAppContainer');

  const {
    todos,
    chosenTodo,
    onAdd,
    remove,
    cancelUpdate,
    update,
    setChosenTodo,
  } = useTodoApp();

  return (
    <TodoApp
      todos={todos}
      chosenTodo={chosenTodo}
      onEdit={setChosenTodo}
      onRemove={remove}
      onUpdate={update}
      onCancelUpdate={cancelUpdate}
      onAdd={onAdd}
    />
  );
};

export default TodoAppContainer;

// ng-unit-testing/src/app/todo-app/components/todo-app-container/todo-app-container.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoService } from '../../services/todo.service';

@Component({
  selector: 'app-todo-app-container',
  templateUrl: './todo-app-container.component.html',
  styleUrls: ['./todo-app-container.component.css']
})
export class TodoAppContainerComponent implements OnInit {

  constructor(public todoService: TodoService) { }

  ngOnInit() {
  }

}

<app-todo-app
  [todos]="todoService.todos | async"
  [chosenTodo]="todoService.chosenTodo | async"
  (onAdd)="todoService.onAdd()"
  (onCancelUpdate)="todoService.cancelUpdate()"
  (onEdit)="todoService.setChosenTodo($event)"
  (onRemove)="todoService.remove($event)"
  (onUpdate)="todoService.update($event)">
</app-todo-app>
